version: '3.9'

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

networks:
  default:
    name: taggy
    driver: bridge

services:
  # ******************
  # Core Demo Services
  # ******************
  rssservice:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-rssservice
    container_name: rss-service
    build:
      context: ./
      dockerfile: ./src/rssservice/Dockerfile
      cache_from:
        - ${IMAGE_NAME}:${IMAGE_VERSION}-rssservice
    deploy:
      resources:
        limits:
          memory: 20M
    ports:
      - ${RSS_SERVICE_PORT}:${RSS_SERVICE_PORT}
    restart: unless-stopped
    environment:
      - RSS_SERVICE_PORT
      - RSS_SERVICE_MONGODB_PORT
      - RSS_SERVICE_MONGODB_ADDR
      - RSS_SERVICE_MONGODB_NAME
      - KAFKA_SERVICE_ADDR
    depends_on:
      rss-mongodb:
        condition: service_started

  # ******************
  # Dependent Services
  # ******************
  # mongodb used by rssservice
  rss-mongodb:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - ./volumes/rss-mongodb-data:/data/db
    ports:
      - 27018:27017 # for local dev
  kafka:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-kafka
    container_name: kafka
    build:
      context: ./
      dockerfile: ./src/kafka/Dockerfile
      cache_from:
        - ${IMAGE_NAME}:${IMAGE_VERSION}-kafka
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      - OTEL_RESOURCE_ATTRIBUTES
      - OTEL_SERVICE_NAME=kafka
      - KAFKA_HEAP_OPTS=-Xmx200m -Xms200m
    healthcheck:
      test: nc -z kafka 9092
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
    - 9092:9092 # for local dev
    logging: *logging
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
    - 8085:8080