export const dataSet2 = {
  nodes: [
    { id: "React", group: 1, tagId: 12312 },
    { id: "Redux", group: 1 },
    { id: "coffee", group: 2 },
    { id: "coffee1", group: 2 },
    { id: "coffee2", group: 2 },
    { id: "coffee3", group: 2 },
    { id: "coffee4", group: 2 },
    { id: "coffee5", group: 2 },
    { id: "coffee6", group: 2 },
    { id: "coffee7", group: 2 },
    { id: "coffee8", group: 2 },
    { id: "coffee9", group: 2 },
    { id: "coffee10", group: 2 },
  ],
  links: [
    {
      source: "React",
      target: "coffee",
      value: "1",
      distance: 50,
    },
    {
      source: "React",
      target: "Redux",
      value: "100",
    },
    {
      source: "React",
      target: "coffee1",
      value: "1",
      distance: 50,
    },
    {
      source: "React",
      target: "coffee2",
      value: "1",
      distance: 50,
    },
    {
      source: "React",
      target: "coffee3",
      value: "1",
      distance: 50,
    },
    {
      source: "coffee2",
      target: "coffee4",
      value: "1",
      distance: 50,
    },
    {
      source: "coffee",
      target: "coffee5",
      value: "1",
      distance: 50,
    },
    {
      source: "coffee",
      target: "coffee9",
      value: "100",
    },
    {
      source: "coffee",
      target: "coffee10",
      value: "100",
    },
  ],
};
