receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/loggingexporter/README.md 
  logging: # Exports data to the console via zap.Logger. 

  #  https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter
  
  prometheus:
#    endpoint: "otelcol:9464"  # the address on which metrics will be exposed
    endpoint: "localhost:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
  zipkin:
      endpoint: "http://zipkin:9411/api/v2/spans"
      format: proto

processors:
  batch: # detail documentation: https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor/README.md


connectors:
  spanmetrics: # A successor to span metrics processor? should study more later

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, spanmetrics, zipkin]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
